name: Build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: tumi5/latex
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Build template
      run: make
    - name: Upload log files, if building failed
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: log files
        path: ofj-template.log
    - name: Upload resulting PDF
      uses: actions/upload-artifact@v3
      with:
        name: template pdf
        path: |
          ofj-template.pdf
